##
## 配置文件中的属性名称全部小写，对应的解析类首字母大写，不然会解析失败
##  常量配置文件
##
serverversion: "3.1.0"
brokerurl : "tcp://:1883" # mqtt服务
wsbrokerurl : ":8883" # ws路径
cluster:
    enabled: false
    name : "node3" # 当前节点name，不要与其它节点冲突
    hostip : "udp://127.0.0.1:8763" #当前节点的外网访问地址
    zkurl : "10.112.26.131:2181" ## zk集群的写法 10.112.26.131:2181,10.112.26.131:2181
    zktimeout : 5 # zk超时 单位秒
    zkmqroot : "/mqRoot" # zk根
    sharejoin: "/" # 共享订阅中，主题与相应的共享名称的拼接符，默认为 '/'
# 下面mybuff没啥用的，只能写死在service/buffer:go里面:
mybuff:
    buffersize: 262144  #1024 * 256
    readblocksize: 8192
    writeblocksize: 8192

# 服务器启动的相关配置类
# 系统默认配置
defaultconst:
  # 默认配置
    keepalive: 300
    connecttimeout: 2
    acktimeout: 20
    timeoutretries: 3
    #      //下面两个最好一样,要是修改了要去这两个文件中（sessions/memprovider.go和topics/memtopics.go）修改对应的
    #      //因为不能在那里面要用这个，不然会引起相互依赖的
    #      //还有redis的，也在上面两个文件包下
    sessionsprovider: "mem"  #//保存至内存中
    topicsprovider: "mem"
    authenticator: "" # 不填则会采用默认，开启身份验证的验证钩子，可选【"default","mysql","redis"】
    redis:
      redisurl: "10.112.26.131:6379"
      password: ""
      db: 1
      rsize: 15 #redis池大小
    mysql:
      mysqlurl: "10.112.26.131:3306"
      account: "root"
      password: "root"
      database: "mqtt"
      mysqlpoolsize : 10 # 数据库池化大小
# 默认账号密码，测试用
myauth:
  open: true  #开启测试账号
  defaultname: "admin"
  defaultpwd: "password"